# Libraries and Data Import

In [22]:
import json
import pandas as pd

In [23]:
with open('stations_data.json', 'r') as f:
    raw_data = json.load(f)

df_data = pd.DataFrame(raw_data)
len(raw_data)
df_data.shape

(19716, 31)

# Data Analysis

In [24]:
df_data.keys()

Index(['DataProvider', 'OperatorInfo', 'UsageType', 'StatusType',
       'SubmissionStatus', 'UserComments', 'PercentageSimilarity',
       'MediaItems', 'IsRecentlyVerified', 'DateLastVerified', 'ID', 'UUID',
       'ParentChargePointID', 'DataProviderID', 'DataProvidersReference',
       'OperatorID', 'OperatorsReference', 'UsageTypeID', 'UsageCost',
       'AddressInfo', 'Connections', 'NumberOfPoints', 'GeneralComments',
       'DatePlanned', 'DateLastConfirmed', 'StatusTypeID',
       'DateLastStatusUpdate', 'MetadataValues', 'DataQualityLevel',
       'DateCreated', 'SubmissionStatusTypeID'],
      dtype='str')

In [25]:
df_data.head()

,DataProvider,OperatorInfo,UsageType,StatusType,SubmissionStatus,UserComments,PercentageSimilarity,MediaItems,IsRecentlyVerified,DateLastVerified,...,NumberOfPoints,GeneralComments,DatePlanned,DateLastConfirmed,StatusTypeID,DateLastStatusUpdate,MetadataValues,DataQualityLevel,DateCreated,SubmissionStatusTypeID
0,"{'WebsiteURL': 'http://openchargemap.org', 'Co...",{'WebsiteURL': 'https://www.iberdrola.es/clien...,"{'IsPayAtLocation': False, 'IsMembershipRequir...","{'IsOperational': True, 'IsUserSelectable': Tr...","{'IsLive': True, 'ID': 200, 'Title': 'Submissi...",None,None,None,True,2026-03-04T23:03:00Z,...,4.0,NaN,None,None,50,2026-03-04T23:03:00Z,None,1,2026-03-04T23:03:00Z,200
1,"{'WebsiteURL': 'http://openchargemap.org', 'Co...",{'WebsiteURL': 'https://www.iberdrola.es/clien...,"{'IsPayAtLocation': False, 'IsMembershipRequir...","{'IsOperational': True, 'IsUserSelectable': Tr...","{'IsLive': True, 'ID': 200, 'Title': 'Submissi...",None,None,None,True,2026-03-04T23:02:00Z,...,6.0,NaN,None,None,50,2026-03-04T23:02:00Z,None,1,2026-03-04T23:02:00Z,200
2,"{'WebsiteURL': 'http://openchargemap.org', 'Co...","{'WebsiteURL': None, 'Comments': 'For use when...","{'IsPayAtLocation': False, 'IsMembershipRequir...","{'IsOperational': True, 'IsUserSelectable': Tr...","{'IsLive': True, 'ID': 200, 'Title': 'Submissi...",None,None,None,True,2026-03-04T22:46:00Z,...,1.0,NaN,None,None,50,2026-03-04T22:46:00Z,None,1,2026-03-04T22:46:00Z,200
3,"{'WebsiteURL': 'http://openchargemap.org', 'Co...",{'WebsiteURL': 'https://www.repsol.es/particul...,"{'IsPayAtLocation': None, 'IsMembershipRequire...","{'IsOperational': True, 'IsUserSelectable': Tr...","{'IsLive': True, 'ID': 200, 'Title': 'Submissi...",None,None,None,True,2026-03-01T17:31:00Z,...,2.0,NaN,None,None,50,2026-03-01T17:31:00Z,None,1,2026-03-01T17:31:00Z,200
4,"{'WebsiteURL': 'http://openchargemap.org', 'Co...",{'WebsiteURL': 'https://www.aparcamentsbsm.cat...,"{'IsPayAtLocation': None, 'IsMembershipRequire...","{'IsOperational': True, 'IsUserSelectable': Tr...","{'IsLive': True, 'ID': 200, 'Title': 'Submissi...",None,None,None,True,2026-03-01T17:03:00Z,...,4.0,NaN,None,None,50,2026-03-01T17:03:00Z,None,1,2026-03-01T17:03:00Z,200

## Main operators

In [26]:
print(df_data["OperatorID"].value_counts().sort_values(ascending=False).to_string())

OperatorID
45.0      3684
2247.0    2501
207.0     1769
91.0      1548
3499.0    1184
1.0       1062
3377.0     753
3401.0     669
3459.0     562
3276.0     503
3324.0     482
3283.0     459
3371.0     382
3583.0     354
3556.0     331
3571.0     276
3750.0     218
3557.0     206
38.0       198
3464.0     169
3550.0     147
3279.0     134
3584.0     128
3798.0     121
3305.0     121
3588.0     114
3577.0     107
3559.0     107
3275.0     106
3534.0     104
3786.0      83
103.0       77
3960.0      74
3552.0      66
3945.0      63
3956.0      62
3975.0      58
3930.0      50
3299.0      50
200.0       44
3558.0      40
3572.0      33
3785.0      32
3955.0      31
3523.0      29
3809.0      27
3608.0      27
3949.0      24
3632.0      24
3489.0      23
3816.0      23
3553.0      22
3889.0      22
3671.0      19
3586.0      18
3880.0      18
3704.0      17
3312.0      15
3770.0      14
3947.0      13
55.0        12
210.0       11
3772.0      10
23.0        10
3278.0       9
212.0        9
3954.0       8
209.0        8
3790.0       6
206.0        6
3296.0       4
3732.0       4
3327.0       4
3589.0       3
3573.0       3
74.0         2
3551.0       1
3479.0       1
196.0        1

In [27]:
op_45 = df_data.loc[df_data["OperatorID"] == 45].head(1)["OperatorInfo"].iloc[0]
times_op_45 = df_data.loc[df_data["OperatorID"] == 45].shape[0]
print(f"1. ID 45 ({times_op_45} occurrences):\t", op_45["Title"])

op_2247 = df_data.loc[df_data["OperatorID"] == 2247].head(1)["OperatorInfo"].iloc[0]
times_op_2247 = df_data.loc[df_data["OperatorID"] == 2247].shape[0]
print(f"2. ID 2247 ({times_op_2247} occurrences):\t", op_2247["Title"])

op_207 = df_data.loc[df_data["OperatorID"] == 207].head(1)["OperatorInfo"].iloc[0]
times_op_207 = df_data.loc[df_data["OperatorID"] == 207].shape[0]
print(f"3. ID 207 ({times_op_207} occurrences):\t", op_207["Title"])

op_91 = df_data.loc[df_data["OperatorID"] == 91].head(1)["OperatorInfo"].iloc[0]
times_op_91 = df_data.loc[df_data["OperatorID"] == 91].shape[0]
print(f"4. ID 91 ({times_op_91} occurrences):\t", op_91["Title"])

op_3499 = df_data.loc[df_data["OperatorID"] == 3499].head(1)["OperatorInfo"].iloc[0]
times_op_3499 = df_data.loc[df_data["OperatorID"] == 3499].shape[0]
print(f"5. ID 3499 ({times_op_3499} occurrences):\t", op_3499["Title"])

op_1 = df_data.loc[df_data["OperatorID"] == 1].head(1)["OperatorInfo"].iloc[0]
times_op_1 = df_data.loc[df_data["OperatorID"] == 1].shape[0]
print(f"6. ID 1 ({times_op_1} occurrences):\t", op_1["Title"])

op_3377 = df_data.loc[df_data["OperatorID"] == 3377].head(1)["OperatorInfo"].iloc[0]
times_op_3377 = df_data.loc[df_data["OperatorID"] == 3377].shape[0]
print(f"7. ID 3377 ({times_op_3377} occurrences):\t", op_3377["Title"])

op_3401 = df_data.loc[df_data["OperatorID"] == 3401].head(1)["OperatorInfo"].iloc[0]
times_op_3401 = df_data.loc[df_data["OperatorID"] == 3401].shape[0]
print(f"8. ID 3401 ({times_op_3401} occurrences):\t", op_3401["Title"])

1. ID 45 (3684 occurrences):	 (Business Owner at Location)
2. ID 2247 (2501 occurrences):	 Iberdrola | BP Pulse (ES)
3. ID 207 (1769 occurrences):	 Endesa
4. ID 91 (1548 occurrences):	 Repsol - Ibil (ES)
5. ID 3499 (1184 occurrences):	 Mercadona
6. ID 1 (1062 occurrences):	 (Unknown Operator)
7. ID 3377 (753 occurrences):	 eTecnic
8. ID 3401 (669 occurrences):	 Electromaps

## Chargers

In [28]:
st_example = df_data.head(1).to_dict(orient="records")[0]
charg = pd.DataFrame(st_example["Connections"])
charg

,ID,ConnectionTypeID,ConnectionType,Reference,StatusTypeID,StatusType,LevelID,Level,Amps,Voltage,PowerKW,CurrentTypeID,CurrentType,Quantity,Comments
0,805482,33,"{'FormalName': 'IEC 62196-3 Configuration FF',...",None,50,"{'IsOperational': True, 'IsUserSelectable': Tr...",3,"{'Comments': '40KW and Higher', 'IsFastChargeC...",150,1000,60,30,"{'Description': 'Direct Current', 'ID': 30, 'T...",4,None

In [29]:
charg.keys()

Index(['ID', 'ConnectionTypeID', 'ConnectionType', 'Reference', 'StatusTypeID',
       'StatusType', 'LevelID', 'Level', 'Amps', 'Voltage', 'PowerKW',
       'CurrentTypeID', 'CurrentType', 'Quantity', 'Comments'],
      dtype='str')

In [30]:
df_data["Connections"]

0        [{'ID': 805482, 'ConnectionTypeID': 33, 'Conne...
1        [{'ID': 805481, 'ConnectionTypeID': 33, 'Conne...
2        [{'ID': 805478, 'ConnectionTypeID': 33, 'Conne...
3        [{'ID': 805260, 'ConnectionTypeID': 25, 'Conne...
4        [{'ID': 805259, 'ConnectionTypeID': 28, 'Conne...
                               ...
19711    [{'ID': 25886, 'ConnectionTypeID': 28, 'Connec...
19712    [{'ID': 25817, 'ConnectionTypeID': 25, 'Connec...
19713    [{'ID': 24788, 'ConnectionTypeID': 25, 'Connec...
19714    [{'ID': 89854, 'ConnectionTypeID': 28, 'Connec...
19715    [{'ID': 6142, 'ConnectionTypeID': 1036, 'Conne...
Name: Connections, Length: 19716, dtype: object

In [31]:
added = set()
types = list()
all_chargers = list()

for station in raw_data:
    for c in station["Connections"]:
        all_chargers.append(c)
        if c["ConnectionTypeID"] not in added:
            print(c)
            types.append(c)
            added.add(c["ConnectionTypeID"])

len(types)

{'ID': 805482, 'ConnectionTypeID': 33, 'ConnectionType': {'FormalName': 'IEC 62196-3 Configuration FF', 'IsDiscontinued': False, 'IsObsolete': False, 'ID': 33, 'Title': 'CCS (Type 2)'}, 'Reference': None, 'StatusTypeID': 50, 'StatusType': {'IsOperational': True, 'IsUserSelectable': True, 'ID': 50, 'Title': 'Operational'}, 'LevelID': 3, 'Level': {'Comments': '40KW and Higher', 'IsFastChargeCapable': True, 'ID': 3, 'Title': 'Level 3:  High (Over 40kW)'}, 'Amps': 150, 'Voltage': 1000, 'PowerKW': 60, 'CurrentTypeID': 30, 'CurrentType': {'Description': 'Direct Current', 'ID': 30, 'Title': 'DC'}, 'Quantity': 4, 'Comments': None}
{'ID': 805260, 'ConnectionTypeID': 25, 'ConnectionType': {'FormalName': 'IEC 62196-2 Type 2', 'IsDiscontinued': False, 'IsObsolete': False, 'ID': 25, 'Title': 'Type 2 (Socket Only)'}, 'Reference': None, 'StatusTypeID': 50, 'StatusType': {'IsOperational': True, 'IsUserSelectable': True, 'ID': 50, 'Title': 'Operational'}, 'LevelID': 2, 'Level': {'Comments': 'Over 2 kW, usually non-domestic socket type', 'IsFastChargeCapable': False, 'ID': 2, 'Title': 'Level 2 : Medium (Over 2kW)'}, 'Amps': None, 'Voltage': None, 'PowerKW': 7.4, 'CurrentTypeID': 10, 'CurrentType': {'Description': 'Alternating Current - Single Phase', 'ID': 10, 'Title': 'AC (Single-Phase)'}, 'Quantity': 2, 'Comments': None}
{'ID': 805259, 'ConnectionTypeID': 28, 'ConnectionType': {'FormalName': 'CEE 7/4', 'IsDiscontinued': False, 'IsObsolete': False, 'ID': 28, 'Title': 'CEE 7/4 - Schuko - Type F'}, 'Reference': None, 'StatusTypeID': 50, 'StatusType': {'IsOperational': True, 'IsUserSelectable': True, 'ID': 50, 'Title': 'Operational'}, 'LevelID': 2, 'Level': {'Comments': 'Over 2 kW, usually non-domestic socket type', 'IsFastChargeCapable': False, 'ID': 2, 'Title': 'Level 2 : Medium (Over 2kW)'}, 'Amps': None, 'Voltage': None, 'PowerKW': 3.5, 'CurrentTypeID': 10, 'CurrentType': {'Description': 'Alternating Current - Single Phase', 'ID': 10, 'Title': 'AC (Single-Phase)'}, 'Quantity': 4, 'Comments': None}
{'ID': 805252, 'ConnectionTypeID': 2, 'ConnectionType': {'FormalName': 'IEC 62196-3 Configuration AA', 'IsDiscontinued': None, 'IsObsolete': None, 'ID': 2, 'Title': 'CHAdeMO'}, 'Reference': None, 'StatusTypeID': 50, 'StatusType': {'IsOperational': True, 'IsUserSelectable': True, 'ID': 50, 'Title': 'Operational'}, 'LevelID': 3, 'Level': {'Comments': '40KW and Higher', 'IsFastChargeCapable': True, 'ID': 3, 'Title': 'Level 3:  High (Over 40kW)'}, 'Amps': None, 'Voltage': None, 'PowerKW': 80, 'CurrentTypeID': 30, 'CurrentType': {'Description': 'Direct Current', 'ID': 30, 'Title': 'DC'}, 'Quantity': 1, 'Comments': None}
{'ID': 804207, 'ConnectionTypeID': 1036, 'ConnectionType': {'FormalName': 'IEC 62196-2', 'IsDiscontinued': False, 'IsObsolete': False, 'ID': 1036, 'Title': 'Type 2 (Tethered Connector) '}, 'Reference': None, 'StatusTypeID': 50, 'StatusType': {'IsOperational': True, 'IsUserSelectable': True, 'ID': 50, 'Title': 'Operational'}, 'LevelID': 2, 'Level': {'Comments': 'Over 2 kW, usually non-domestic socket type', 'IsFastChargeCapable': False, 'ID': 2, 'Title': 'Level 2 : Medium (Over 2kW)'}, 'Amps': None, 'Voltage': None, 'PowerKW': 22, 'CurrentTypeID': 20, 'CurrentType': {'Description': 'Alternating Current - Three Phase', 'ID': 20, 'Title': 'AC (Three-Phase)'}, 'Quantity': 1, 'Comments': None}
{'ID': 791731, 'ConnectionTypeID': 0, 'ConnectionType': {'FormalName': 'Not Specified', 'IsDiscontinued': None, 'IsObsolete': None, 'ID': 0, 'Title': 'Unknown'}, 'Reference': None, 'StatusTypeID': 50, 'StatusType': {'IsOperational': True, 'IsUserSelectable': True, 'ID': 50, 'Title': 'Operational'}, 'LevelID': None, 'Level': None, 'Amps': None, 'Voltage': None, 'PowerKW': None, 'CurrentTypeID': None, 'CurrentType': None, 'Quantity': 1, 'Comments': None}
{'ID': 776674, 'ConnectionTypeID': 1, 'ConnectionType': {'FormalName': 'SAE J1772-2009', 'IsDiscontinued': None, 'IsObsolete': None, 'ID': 1, 'Title': 'Type 1 (J1772)'}, 'Reference': None, 'StatusTypeID': 50, 'StatusType': {'IsOperational': True, 'IsUserSelectable': True, 'ID': 50, 'Title': 'Operational'}, 'LevelID': 2, 'Level': {'Comments': 'Over 2 kW, usually non-domestic socket type', 'IsFastChargeCapable': False, 'ID': 2, 'Title': 'Level 2 : Medium (Over 2kW)'}, 'Amps': None, 'Voltage': None, 'PowerKW': 7.4, 'CurrentTypeID': 10, 'CurrentType': {'Description': 'Alternating Current - Single Phase', 'ID': 10, 'Title': 'AC (Single-Phase)'}, 'Quantity': 1, 'Comments': None}
{'ID': 776657, 'ConnectionTypeID': 17, 'ConnectionType': {'FormalName': None, 'IsDiscontinued': False, 'IsObsolete': False, 'ID': 17, 'Title': 'CEE 5 Pin'}, 'Reference': None, 'StatusTypeID': 50, 'StatusType': {'IsOperational': True, 'IsUserSelectable': True, 'ID': 50, 'Title': 'Operational'}, 'LevelID': 2, 'Level': {'Comments': 'Over 2 kW, usually non-domestic socket type', 'IsFastChargeCapable': False, 'ID': 2, 'Title': 'Level 2 : Medium (Over 2kW)'}, 'Amps': 16, 'Voltage': 400, 'PowerKW': 11, 'CurrentTypeID': 20, 'CurrentType': {'Description': 'Alternating Current - Three Phase', 'ID': 20, 'Title': 'AC (Three-Phase)'}, 'Quantity': 2, 'Comments': None}
{'ID': 602251, 'ConnectionTypeID': 30, 'ConnectionType': {'FormalName': None, 'IsDiscontinued': False, 'IsObsolete': False, 'ID': 30, 'Title': 'Tesla (Model S/X)'}, 'Reference': None, 'StatusTypeID': 50, 'StatusType': {'IsOperational': True, 'IsUserSelectable': True, 'ID': 50, 'Title': 'Operational'}, 'LevelID': 2, 'Level': {'Comments': 'Over 2 kW, usually non-domestic socket type', 'IsFastChargeCapable': False, 'ID': 2, 'Title': 'Level 2 : Medium (Over 2kW)'}, 'Amps': 16, 'Voltage': 400, 'PowerKW': 11, 'CurrentTypeID': 10, 'CurrentType': {'Description': 'Alternating Current - Single Phase', 'ID': 10, 'Title': 'AC (Single-Phase)'}, 'Quantity': 1, 'Comments': None}
{'ID': 565209, 'ConnectionTypeID': 16, 'ConnectionType': {'FormalName': None, 'IsDiscontinued': False, 'IsObsolete': False, 'ID': 16, 'Title': 'CEE 3 Pin'}, 'Reference': None, 'StatusTypeID': 50, 'StatusType': {'IsOperational': True, 'IsUserSelectable': True, 'ID': 50, 'Title': 'Operational'}, 'LevelID': 2, 'Level': {'Comments': 'Over 2 kW, usually non-domestic socket type', 'IsFastChargeCapable': False, 'ID': 2, 'Title': 'Level 2 : Medium (Over 2kW)'}, 'Amps': None, 'Voltage': None, 'PowerKW': 3, 'CurrentTypeID': 10, 'CurrentType': {'Description': 'Alternating Current - Single Phase', 'ID': 10, 'Title': 'AC (Single-Phase)'}, 'Quantity': 2, 'Comments': None}
{'ID': 452085, 'ConnectionTypeID': 32, 'ConnectionType': {'FormalName': 'IEC 62196-3 Configuration EE', 'IsDiscontinued': False, 'IsObsolete': False, 'ID': 32, 'Title': 'CCS (Type 1)'}, 'Reference': None, 'StatusTypeID': 50, 'StatusType': {'IsOperational': True, 'IsUserSelectable': True, 'ID': 50, 'Title': 'Operational'}, 'LevelID': 3, 'Level': {'Comments': '40KW and Higher', 'IsFastChargeCapable': True, 'ID': 3, 'Title': 'Level 3:  High (Over 40kW)'}, 'Amps': None, 'Voltage': None, 'PowerKW': 50, 'CurrentTypeID': 30, 'CurrentType': {'Description': 'Direct Current', 'ID': 30, 'Title': 'DC'}, 'Quantity': 1, 'Comments': None}
{'ID': 356044, 'ConnectionTypeID': 13, 'ConnectionType': {'FormalName': 'Europlug 2-Pin (CEE 7/16)', 'IsDiscontinued': False, 'IsObsolete': False, 'ID': 13, 'Title': 'Europlug 2-Pin (CEE 7/16)'}, 'Reference': None, 'StatusTypeID': 50, 'StatusType': {'IsOperational': True, 'IsUserSelectable': True, 'ID': 50, 'Title': 'Operational'}, 'LevelID': 2, 'Level': {'Comments': 'Over 2 kW, usually non-domestic socket type', 'IsFastChargeCapable': False, 'ID': 2, 'Title': 'Level 2 : Medium (Over 2kW)'}, 'Amps': None, 'Voltage': None, 'PowerKW': 3.7, 'CurrentTypeID': 10, 'CurrentType': {'Description': 'Alternating Current - Single Phase', 'ID': 10, 'Title': 'AC (Single-Phase)'}, 'Quantity': 1, 'Comments': None}
{'ID': 349571, 'ConnectionTypeID': 27, 'ConnectionType': {'FormalName': 'SAE J3400', 'IsDiscontinued': False, 'IsObsolete': False, 'ID': 27, 'Title': 'NACS / Tesla Supercharger'}, 'Reference': None, 'StatusTypeID': 50, 'StatusType': {'IsOperational': True, 'IsUserSelectable': True, 'ID': 50, 'Title': 'Operational'}, 'LevelID': 3, 'Level': {'Comments': '40KW and Higher', 'IsFastChargeCapable': True, 'ID': 3, 'Title': 'Level 3:  High (Over 40kW)'}, 'Amps': None, 'Voltage': None, 'PowerKW': 150, 'CurrentTypeID': 30, 'CurrentType': {'Description': 'Direct Current', 'ID': 30, 'Title': 'DC'}, 'Quantity': 4, 'Comments': 'V2 (Tesla S/X connector)'}
{'ID': 339902, 'ConnectionTypeID': 29, 'ConnectionType': {'FormalName': 'Type I/AS 3112/CPCS-CCC', 'IsDiscontinued': False, 'IsObsolete': False, 'ID': 29, 'Title': 'Type I (AS 3112)'}, 'Reference': None, 'StatusTypeID': 50, 'StatusType': {'IsOperational': True, 'IsUserSelectable': True, 'ID': 50, 'Title': 'Operational'}, 'LevelID': 2, 'Level': {'Comments': 'Over 2 kW, usually non-domestic socket type', 'IsFastChargeCapable': False, 'ID': 2, 'Title': 'Level 2 : Medium (Over 2kW)'}, 'Amps': None, 'Voltage': None, 'PowerKW': 3.7, 'CurrentTypeID': 10, 'CurrentType': {'Description': 'Alternating Current - Single Phase', 'ID': 10, 'Title': 'AC (Single-Phase)'}, 'Quantity': 1, 'Comments': None}
{'ID': 338590, 'ConnectionTypeID': 18, 'ConnectionType': {'FormalName': None, 'IsDiscontinued': False, 'IsObsolete': False, 'ID': 18, 'Title': 'CEE+ 7 Pin'}, 'Reference': None, 'StatusTypeID': 50, 'StatusType': {'IsOperational': True, 'IsUserSelectable': True, 'ID': 50, 'Title': 'Operational'}, 'LevelID': 2, 'Level': {'Comments': 'Over 2 kW, usually non-domestic socket type', 'IsFastChargeCapable': False, 'ID': 2, 'Title': 'Level 2 : Medium (Over 2kW)'}, 'Amps': None, 'Voltage': None, 'PowerKW': 22, 'CurrentTypeID': 20, 'CurrentType': {'Description': 'Alternating Current - Three Phase', 'ID': 20, 'Title': 'AC (Three-Phase)'}, 'Quantity': 2, 'Comments': None}
{'ID': 121618, 'ConnectionTypeID': 4, 'ConnectionType': {'FormalName': None, 'IsDiscontinued': None, 'IsObsolete': None, 'ID': 4, 'Title': 'Blue Commando (2P+E)'}, 'Reference': None, 'StatusTypeID': 50, 'StatusType': {'IsOperational': True, 'IsUserSelectable': True, 'ID': 50, 'Title': 'Operational'}, 'LevelID': 2, 'Level': {'Comments': 'Over 2 kW, usually non-domestic socket type', 'IsFastChargeCapable': False, 'ID': 2, 'Title': 'Level 2 : Medium (Over 2kW)'}, 'Amps': 16, 'Voltage': 230, 'PowerKW': 3.7, 'CurrentTypeID': 10, 'CurrentType': {'Description': 'Alternating Current - Single Phase', 'ID': 10, 'Title': 'AC (Single-Phase)'}, 'Quantity': 1, 'Comments': None}

16

In [32]:
all_chargers_df = pd.DataFrame(all_chargers)
all_chargers_df["ConnectionTypeID"].value_counts()

ConnectionTypeID
25      12775
33       7901
2        3932
1036     3745
28       1896
30        375
16         80
17         77
1          24
0          14
13          8
29          4
18          3
4           2
32          1
27          1
Name: count, dtype: int64

In [33]:
con_25 = all_chargers_df.loc[all_chargers_df["ConnectionTypeID"] == 25].head(1)["ConnectionType"].iloc[0]
times_conn_25 = all_chargers_df.loc[all_chargers_df["ConnectionTypeID"] == 25].shape[0]
print(f"1. ID 25 ({times_conn_25} occurrences):\t", con_25["FormalName"], "\t\t", con_25["Title"])

con_33 = all_chargers_df.loc[all_chargers_df["ConnectionTypeID"] == 33].head(1)["ConnectionType"].iloc[0]
times_conn_33 = all_chargers_df.loc[all_chargers_df["ConnectionTypeID"] == 33].shape[0]
print(f"2. ID 33 ({times_conn_33} occurrences):\t", con_33["FormalName"], "\t\t", con_33["Title"])

con_2 = all_chargers_df.loc[all_chargers_df["ConnectionTypeID"] == 2].head(1)["ConnectionType"].iloc[0]
times_conn_2 = all_chargers_df.loc[all_chargers_df["ConnectionTypeID"] == 2].shape[0]
print(f"3. ID 2 ({times_conn_2} occurrences):\t", con_2["FormalName"], "\t\t", con_2["Title"])

con_1036 = all_chargers_df.loc[all_chargers_df["ConnectionTypeID"] == 1036].head(1)["ConnectionType"].iloc[0]
times_conn_1036 = all_chargers_df.loc[all_chargers_df["ConnectionTypeID"] == 1036].shape[0]
print(f"4. ID 1036 ({times_conn_1036} occurrences):\t", con_1036["FormalName"], "\t\t", con_1036["Title"])

con_28 = all_chargers_df.loc[all_chargers_df["ConnectionTypeID"] == 28].head(1)["ConnectionType"].iloc[0]
times_conn_28 = all_chargers_df.loc[all_chargers_df["ConnectionTypeID"] == 28].shape[0]
print(f"5. ID 28 ({times_conn_28} occurrences):\t", con_28["FormalName"], "\t\t", con_28["Title"])

con_30 = all_chargers_df.loc[all_chargers_df["ConnectionTypeID"] == 30].head(1)["ConnectionType"].iloc[0]
times_conn_30 = all_chargers_df.loc[all_chargers_df["ConnectionTypeID"] == 30].shape[0]
print(f"6. ID 30 ({times_conn_30} occurrences):\t", con_30["FormalName"], "\t\t", con_30["Title"])

con_16 = all_chargers_df.loc[all_chargers_df["ConnectionTypeID"] == 16].head(1)["ConnectionType"].iloc[0]
times_conn_16 = all_chargers_df.loc[all_chargers_df["ConnectionTypeID"] == 16].shape[0]
print(f"7. ID 16 ({times_conn_16} occurrences):\t", con_16["FormalName"], "\t\t", con_16["Title"])

con_17 = all_chargers_df.loc[all_chargers_df["ConnectionTypeID"] == 17].head(1)["ConnectionType"].iloc[0]
times_conn_17 = all_chargers_df.loc[all_chargers_df["ConnectionTypeID"] == 17].shape[0]
print(f"8. ID 17 ({times_conn_17} occurrences):\t", con_17["FormalName"], "\t\t", con_17["Title"])

con_1 = all_chargers_df.loc[all_chargers_df["ConnectionTypeID"] == 1].head(1)["ConnectionType"].iloc[0]
times_conn_1 = all_chargers_df.loc[all_chargers_df["ConnectionTypeID"] == 1].shape[0]
print(f"9. ID 1 ({times_conn_1} occurrences):\t", con_1["FormalName"], "\t\t", con_1["Title"])

con_0 = all_chargers_df.loc[all_chargers_df["ConnectionTypeID"] == 0].head(1)["ConnectionType"].iloc[0]
times_conn_0 = all_chargers_df.loc[all_chargers_df["ConnectionTypeID"] == 0].shape[0]
print(f"10. ID 0 ({times_conn_0} occurrences):\t", con_0["FormalName"], "\t\t", con_0["Title"])

con_13 = all_chargers_df.loc[all_chargers_df["ConnectionTypeID"] == 13].head(1)["ConnectionType"].iloc[0]
times_conn_13 = all_chargers_df.loc[all_chargers_df["ConnectionTypeID"] == 13].shape[0]
print(f"11. ID 13 ({times_conn_13} occurrences):\t", con_13["FormalName"], "\t\t", con_13["Title"])

con_29 = all_chargers_df.loc[all_chargers_df["ConnectionTypeID"] == 29].head(1)["ConnectionType"].iloc[0]
times_conn_29 = all_chargers_df.loc[all_chargers_df["ConnectionTypeID"] == 29].shape[0]
print(f"12. ID 29 ({times_conn_29} occurrences):\t", con_29["FormalName"], "\t\t", con_29["Title"])

con_18 = all_chargers_df.loc[all_chargers_df["ConnectionTypeID"] == 18].head(1)["ConnectionType"].iloc[0]
times_conn_18 = all_chargers_df.loc[all_chargers_df["ConnectionTypeID"] == 18].shape[0]
print(f"13. ID 18 ({times_conn_18} occurrences):\t", con_18["FormalName"], "\t\t", con_18["Title"])

con_4 = all_chargers_df.loc[all_chargers_df["ConnectionTypeID"] == 4].head(1)["ConnectionType"].iloc[0]
times_conn_4 = all_chargers_df.loc[all_chargers_df["ConnectionTypeID"] == 4].shape[0]
print(f"14. ID 4 ({times_conn_4} occurrences):\t", con_4["FormalName"], "\t\t", con_4["Title"])

con_32 = all_chargers_df.loc[all_chargers_df["ConnectionTypeID"] == 32].head(1)["ConnectionType"].iloc[0]
times_conn_32 = all_chargers_df.loc[all_chargers_df["ConnectionTypeID"] == 32].shape[0]
print(f"15. ID 32 ({times_conn_32} occurrences):\t", con_32["FormalName"], "\t\t", con_32["Title"])

con_27 = all_chargers_df.loc[all_chargers_df["ConnectionTypeID"] == 27].head(1)["ConnectionType"].iloc[0]
times_conn_27 = all_chargers_df.loc[all_chargers_df["ConnectionTypeID"] == 27].shape[0]
print(f"16. ID 27 ({times_conn_27} occurrences):\t", con_27["FormalName"], "\t\t", con_27["Title"])

1. ID 25 (12775 occurrences):	 IEC 62196-2 Type 2 		 Type 2 (Socket Only)
2. ID 33 (7901 occurrences):	 IEC 62196-3 Configuration FF 		 CCS (Type 2)
3. ID 2 (3932 occurrences):	 IEC 62196-3 Configuration AA 		 CHAdeMO
4. ID 1036 (3745 occurrences):	 IEC 62196-2 		 Type 2 (Tethered Connector)
5. ID 28 (1896 occurrences):	 CEE 7/4 		 CEE 7/4 - Schuko - Type F
6. ID 30 (375 occurrences):	 None 		 Tesla (Model S/X)
7. ID 16 (80 occurrences):	 None 		 CEE 3 Pin
8. ID 17 (77 occurrences):	 None 		 CEE 5 Pin
9. ID 1 (24 occurrences):	 SAE J1772-2009 		 Type 1 (J1772)
10. ID 0 (14 occurrences):	 Not Specified 		 Unknown
11. ID 13 (8 occurrences):	 Europlug 2-Pin (CEE 7/16) 		 Europlug 2-Pin (CEE 7/16)
12. ID 29 (4 occurrences):	 Type I/AS 3112/CPCS-CCC 		 Type I (AS 3112)
13. ID 18 (3 occurrences):	 None 		 CEE+ 7 Pin
14. ID 4 (2 occurrences):	 None 		 Blue Commando (2P+E)
15. ID 32 (1 occurrences):	 IEC 62196-3 Configuration EE 		 CCS (Type 1)
16. ID 27 (1 occurrences):	 SAE J3400 		 NACS / Tesla Supercharger

In Spain, most of the cars use Type 2 connectors (IDs 25, 33, 1036).

Then, ID 28 (CEE 7/4 Schuko Type F) belongs to common house plugs.

The rest of plugs are very specific or obsolet (like CHAdeMO).

In [34]:
valid_conn = times_conn_25 + times_conn_33 + times_conn_1036 + times_conn_28
print(f"Percentage of valid chargers: {valid_conn / all_chargers_df.shape[0]}")

Percentage of valid chargers: 0.8533951618133472

## Columns Analysis

https://openchargemap.org/develop/api#/schemas/POI

Columns found in the data:
- DataProvider: Source of the data. Not relevant for our system.
- **OperatorInfo: Information about the operator of the charging station. Relevant**
- UsageType: Type of usage (e.g., public, private). We assumme all are selectable. Not relevant for our system.
- **StatusType: Operational status of the station. We discard those that are not operational (e.g., "Disabled", "Inactive")**
- SubmissionStatus: Status of the data submission. Not relevant for our system.
- UserComments: User comments about the station. Not relevant for our system.
- PercentageSimilarity: Null value. Not relevant for our system.
- MediaItems: Media items related to the station. Not relevant for our system.
- IsRecentlyVerified: Whether the station has been recently verified. Not relevant for our system.
- DateLastVerified: Date of the last verification. Not relevant for our system.
- **ID: Unique identifier for the station. Relevant.**
- UUID: Unique identifier for the station. Not relevant for our system.
- ParentChargePointID: Null value. Not relevant for our system.
- DataProviderID: Source of the data. Not relevant for our system.
- DataProvidersReference: Identifier for the operator. Not relevant for our system.
- OperatorID: Identifier for the operator. Not relevant for our system.
- OperatorsReference: Identifier for the operator. Not relevant for our system.
- UsageTypeID: Reference for the type of usage. Not relevant for our system.
- **UsageCost: Cost of using the station. Relevant (if available)**
- **AddressInfo: Information about the station's location. Relevant**
- **Connections: Information about the station's different connection types. Relevant**
- **NumberOfPoints: Number of charging points available at the station. Relevant**
- GeneralComments: General comments about the station. Not relevant for our system.
- DatePlanned: Null value. Not relevant for our system.
- DateLastConfirmed: Null value. Not relevant for our system.
- StatusTypeID: Reference for the operational status. Not relevant for our system.
- DateLastStatusUpdated: Date of the last status update. Not relevant for our system.
- MetadataValues: Null value (>99% of rows). Not relevant for our system.
- DataQualityLevel: Unused value. Not relevant for our system.
- DateCreated: Date of creation of the station entry. Not relevant for our system.
- SubmissionStatusTypeID: Reference for the submission status. Not relevant for our system.

In [35]:
clean_data = df_data.copy()

clean_data = clean_data[["ID", "OperatorInfo", "StatusType", "UsageCost", "AddressInfo", "Connections", "NumberOfPoints"]]

In [36]:
clean_data

,ID,OperatorInfo,StatusType,UsageCost,AddressInfo,Connections,NumberOfPoints
0,479753,{'WebsiteURL': 'https://www.iberdrola.es/clien...,"{'IsOperational': True, 'IsUserSelectable': Tr...","0,45€/kWh","{'ID': 480142, 'Title': 'Parking Puerto Portal...","[{'ID': 805482, 'ConnectionTypeID': 33, 'Conne...",4.0
1,479752,{'WebsiteURL': 'https://www.iberdrola.es/clien...,"{'IsOperational': True, 'IsUserSelectable': Tr...","0,45€/kWh","{'ID': 480141, 'Title': 'Puerto Portals. Capit...","[{'ID': 805481, 'ConnectionTypeID': 33, 'Conne...",6.0
2,479751,"{'WebsiteURL': None, 'Comments': 'For use when...","{'IsOperational': True, 'IsUserSelectable': Tr...",,"{'ID': 480140, 'Title': 'BP Guaza', 'AddressLi...","[{'ID': 805478, 'ConnectionTypeID': 33, 'Conne...",1.0
3,479605,{'WebsiteURL': 'https://www.repsol.es/particul...,"{'IsOperational': True, 'IsUserSelectable': Tr...",NaN,"{'ID': 479994, 'Title': 'Seur Manzanares', 'Ad...","[{'ID': 805260, 'ConnectionTypeID': 25, 'Conne...",2.0
4,479604,{'WebsiteURL': 'https://www.aparcamentsbsm.cat...,"{'IsOperational': True, 'IsUserSelectable': Tr...",Free,"{'ID': 479993, 'Title': 'B:SM Avinguda Diagona...","[{'ID': 805259, 'ConnectionTypeID': 28, 'Conne...",4.0
...,...,...,...,...,...,...,...
19711,23803,{'WebsiteURL': 'https://www.aparcamentsbsm.cat...,"{'IsOperational': True, 'IsUserSelectable': Tr...",Free,"{'ID': 24148, 'Title': 'B:SM 52 - Tarradelles-...","[{'ID': 25886, 'ConnectionTypeID': 28, 'Connec...",1.0
19712,23788,"{'WebsiteURL': 'http://www.edp.pt/', 'Comments...","{'IsOperational': True, 'IsUserSelectable': Tr...","parking fee + 0,20€/kWh (0,01€/min parked with...","{'ID': 24133, 'Title': 'Parking APK2 Mondragon...","[{'ID': 25817, 'ConnectionTypeID': 25, 'Connec...",12.0
19713,23085,"{'WebsiteURL': 'https://www.barterenergy.es/',...","{'IsOperational': True, 'IsUserSelectable': Tr...",NaN,"{'ID': 23430, 'Title': 'Hotel Santos Las Arena...","[{'ID': 24788, 'ConnectionTypeID': 25, 'Connec...",6.0
19714,8784,None,"{'IsOperational': True, 'IsUserSelectable': Tr...",Paying small fee with Prepaid RFID card + cost...,"{'ID': 8681, 'Title': 'Parking Plaza de Cánova...","[{'ID': 89854, 'ConnectionTypeID': 28, 'Connec...",3.0
19715,8724,"{'WebsiteURL': 'http://www.endesa.es/', 'Comme...","{'IsOperational': None, 'IsUserSelectable': Tr...",NaN,"{'ID': 8621, 'Title': 'Endesa Ribera del Loira...","[{'ID': 6142, 'ConnectionTypeID': 1036, 'Conne...",13.0

In [37]:
clean_data.keys()

Index(['ID', 'OperatorInfo', 'StatusType', 'UsageCost', 'AddressInfo',
       'Connections', 'NumberOfPoints'],
      dtype='str')

# Data Cleaning

In [38]:
operators_dict = {
    2247: "Iberdrola",
    207: "Endesa",
    91: "Repsol",
    3499: "Mercadona",
    3377: "Etecnic",
}

In [39]:
clean_data = clean_data[
    clean_data["StatusType"].apply(lambda x: isinstance(x, dict) and x.get("Title") == "Operational")
]

print("Not operational:", len(df_data) - len(clean_data))

Not operational: 1382

In [40]:
print(clean_data["AddressInfo"].iloc[0].keys())

dict_keys(['ID', 'Title', 'AddressLine1', 'AddressLine2', 'Town', 'StateOrProvince', 'Postcode', 'CountryID', 'Country', 'Latitude', 'Longitude', 'ContactTelephone1', 'ContactTelephone2', 'ContactEmail', 'AccessComments', 'RelatedURL', 'Distance', 'DistanceUnit'])

In [41]:
data_to_insert = []

for station in raw_data:
    try:
        id = station["ID"]
        name = station["AddressInfo"]["Title"]
        lat = station["AddressInfo"]["Latitude"]
        lon = station["AddressInfo"]["Longitude"]
        conn = station["Connections"]
    except Exception as e:
        continue

    if station["OperatorID"] in operators_dict:
        operator = operators_dict[station["OperatorID"]]
    else:
        operator = "Unknown"

    data_to_insert.append({
        "id": id,
        "name": name,
        "lat": lat,
        "lon": lon,
        "operator": operator,
        "connections": conn,
    })

with open('stations_data_to_insert.json', 'w', encoding='utf-8') as f:
    json.dump(data_to_insert, f, indent=4, ensure_ascii=False)

len(data_to_insert)

19716

# DataBase Population

In [1]:
import json
import pandas as pd

In [2]:
import sys
sys.path.append('../..')

from src.Persistance.db_broker import DBBroker

In [3]:
with open('stations_data_to_insert.json', 'r') as f:
    data_to_insert = json.load(f)

len(data_to_insert)

19716

In [4]:
data_to_insert[0]

{'id': 479753,
 'name': 'Parking Puerto Portals',
 'lat': 39.532410514731566,
 'lon': 2.570002495441713,
 'operator': 'Iberdrola',
 'connections': [{'ID': 805482,
   'ConnectionTypeID': 33,
   'ConnectionType': {'FormalName': 'IEC 62196-3 Configuration FF',
    'IsDiscontinued': False,
    'IsObsolete': False,
    'ID': 33,
    'Title': 'CCS (Type 2)'},
   'Reference': None,
   'StatusTypeID': 50,
   'StatusType': {'IsOperational': True,
    'IsUserSelectable': True,
    'ID': 50,
    'Title': 'Operational'},
   'LevelID': 3,
   'Level': {'Comments': '40KW and Higher',
    'IsFastChargeCapable': True,
    'ID': 3,
    'Title': 'Level 3:  High (Over 40kW)'},
   'Amps': 150,
   'Voltage': 1000,
   'PowerKW': 60,
   'CurrentTypeID': 30,
   'CurrentType': {'Description': 'Direct Current', 'ID': 30, 'Title': 'DC'},
   'Quantity': 4,
   'Comments': None}]}

## Stations

In [5]:
query_operators = "INSERT INTO operators (operator_name) VALUES (%s)"

In [6]:
query_station = """
    INSERT INTO charging_stations (id, station_name, operator_id, location)
    VALUES (?, ?, ?, ST_GeomFromText(?))
"""

In [7]:
operators = ["Unknown", "Iberdrola", "Endesa", "Repsol", "Mercadona", "Etecnic", "Electromaps"]

for op in operators:
    DBBroker().execute_write_query(query_operators, (op,))

2026-05-13 19:22:16,415 - DBBroker - 38 - INFO: Attempting to initialize Database Connection Pool...
2026-05-13 19:22:16,448 - DBBroker - 49 - INFO: Database connection pool established successfully.

In [8]:
batch_size = 10000

for i in range(0, len(data_to_insert), batch_size):
    batch = [
        (item["id"], item["name"], operators.index(item["operator"]) + 1, f'POINT({item["lon"]} {item["lat"]})')
        for item in data_to_insert[i:i+batch_size]
    ]
    DBBroker().execute_many(query_station, batch)

## Chargers

In [9]:
query_charger = """
    INSERT INTO chargers (charging_station_id, power_kw)
    VALUES (?, ?)
"""

In [10]:
def is_valid(charger: dict):
    valid_connections = {25, 33, 1036, 28}
    if charger.get("ConnectionTypeID") not in valid_connections:
        return False

    if charger.get("StatusTypeID") != 50:  # Operational
        return False

    try:
        power_kw = float(charger.get("PowerKW"))
    except (TypeError, ValueError):
        return False

    if power_kw <= 0:
        return False

    return True

In [11]:
for s in data_to_insert:
    for c in s["connections"]:
        if not is_valid(c):
            continue

        station_id = s["id"]
        power_kw = float(c["PowerKW"])

        quantity_raw = c.get("Quantity", 1)
        try:
            quantity = int(quantity_raw) if quantity_raw is not None else 1
        except (TypeError, ValueError):
            quantity = 1
        quantity = max(quantity, 1)

        for _ in range(quantity):
            DBBroker().execute_write_query(query_charger, (station_id, power_kw))